# fly.toml app configuration file generated for portfolio-digialchem on 2024-07-01T11:21:35+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "portfolio-digialchem"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
